name: restaurant_tour
description: Flutter developer coding challenge starter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.6.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  hive: ^2.2.3
  internet_connection_checker: ^2.0.0
  intersperse: ^2.0.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  shimmer: ^3.0.0
  collection: ^1.18.0
  uuid: ^4.5.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
  assets:
    - assets/svg/star.svg
    - assets/png/no_wifi.png
    - assets/png/hero.png
