name: restaurant_tour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10
  #Features
  restaurant:
    path: ./features/restaurant/

  #Platform 
  dependency_injection:
    path: ./platform/dependency_injection/
  ui_kit:
    path: ./platform/ui_kit/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  melos: 6.1.0


flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lora
      fonts:
        - asset: platform/ui_kit/assets/fonts/Lora/Lora-Regular.ttf
          weight: 400
        - asset: platform/ui_kit/assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: platform/ui_kit/assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: platform/ui_kit/assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: platform/ui_kit/assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: platform/ui_kit/assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: platform/ui_kit/assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        
