name: restaurant_tour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  restaurant_gql_client:
    path: packages/restaurant_gql_client
  restaurant_models:
    path: packages/restaurant_models
  restaurant_ui:
    path: packages/restaurant_ui
  restaurant_repository:
    path: packages/restaurant_repository
  equatable: ^2.0.5
  shared_preferences: ^2.3.2



dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600

